require "options"
require "mappings"
require "autocmds"

require "theme"
require "plugins.cmp"
require "plugins.lsp"
require "plugins.treesitter"
require "plugins.telescope"
require "plugins.typst"
require "plugins.cheatsheet"
require "plugins.dap"
require "plugins.misc"
